In [2]:
import torch
print(torch.__version__)

2.3.1


## Introduction to Tensors

### Creating tensors

Scalar - single number - 0D- lower(a)

Vector - a number with direction and magnitude - 1D - lower(b)

Matrix - a two-dimensional array of numbers - 2D - Upper(A)

Tensor - a n-dimensional array of numbers - nD - Upper(B)

In [12]:
# Scalar
scalar = torch.tensor(21)
scalar

tensor(21)

In [14]:
scalar.ndim

0

In [15]:
# Get tensor back as Python int
scalar.item()

21

In [16]:
# Vector
vector = torch.tensor([21, 34])
vector

tensor([21, 34])

In [17]:
vector.ndim

1

In [18]:
vector.shape

torch.Size([2])

In [19]:
# MATRIX
MATRIX = torch.tensor([[21, 34], 
                       [53, 43]])

MATRIX

tensor([[21, 34],
        [53, 43]])

In [20]:
MATRIX.ndim

2

In [21]:
MATRIX.shape

torch.Size([2, 2])

In [59]:
# TENSOR
TENSOR = torch.tensor([
                        [
                            [1, 2, 3],
                            [4, 5, 6],
                            [7, 8, 9],
                            [10, 11, 12]
                        ], [
                            [1, 2, 3],
                            [4, 5, 6],
                            [7, 8, 9],
                            [10, 11, 12]
                        ],
                        [
                            [1, 2, 3],
                            [4, 5, 6],
                            [7, 8, 9],
                            [10, 11, 12]
                        ],
                        [
                            [1, 2, 3],
                            [4, 5, 6],
                            [7, 8, 9],
                            [10, 11, 12]
                        ]
                    ])

TENSOR2 = torch.tensor([
                        [
                            [1, 2, 3, 2, 4],
                            [4, 5, 6, 2, 4],
                            [7, 8, 9, 2, 4],
                            [10, 11, 12, 2, 4],
                            [10, 11, 12, 2, 4]
                        ],
                        [
                            [1, 2, 3, 2, 4],
                            [4, 5, 6, 2, 4],
                            [7, 8, 9, 2, 4],
                            [10, 11, 12, 2, 4],
                            [10, 11, 12, 2, 4]
                        ],
                        [
                            [1, 2, 3, 2, 4],
                            [4, 5, 6, 2, 4],
                            [7, 8, 9, 2, 4],
                            [10, 11, 12, 2, 4],
                            [10, 11, 12, 2, 4]
                        ],
                        [
                            [1, 2, 3, 2, 4],
                            [4, 5, 6, 2, 4],
                            [7, 8, 9, 2, 4],
                            [10, 11, 12, 2, 4],
                            [10, 11, 12, 2, 4]
                        ]
                    ])

#([4, 5, 5])
TENSOR2.shape

torch.Size([4, 5, 5])

In [46]:
TENSOR.ndim

3

In [47]:
TENSOR.shape

torch.Size([2, 4, 3])

In [48]:
TENSOR[0]

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

## Random Tensors

  Why random tensors?

  Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

 'start with random numbers -> look at data -> update random numbers -> look at data -> look at the data'

In [62]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.7606, 0.7758, 0.4410, 0.9316],
        [0.3504, 0.7401, 0.5507, 0.7869],
        [0.4407, 0.6702, 0.1631, 0.2668]])

In [65]:
random_tensor.ndim

2

In [67]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224))

random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [68]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [69]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating range of tensors and tensors-like

In [74]:
# Use torch.range()
one_to_ten = torch.range(0, 10)
one_to_ten

/var/folders/hw/2qqt9k2547j0gf2k4f_hq0lc0000gn/T/ipykernel_4031/2290155656.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  one_to_ten = torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [75]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Tensor datatypes

In [81]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=None,
                               device=None, # What device is your tensor on
                               requires_grad=False)

float_32_tensor.dtype

torch.float32

In [82]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [87]:
int_tensor = torch.tensor([3, 4, 5],
                          dtype=torch.int16)

int_tensor

tensor([3, 4, 5], dtype=torch.int16)

In [88]:
float_32_tensor * int_tensor

tensor([ 9., 24., 45.])

### Getting information from tensors

1. Tensors not right datatype -  to do get datatype from a tensor, can use 'tensor.dtype'
2. Tensors not right shape - to get shape from a tensor, can use 'tensor.shape'
3. Tensors not on the right device - to get device from a tensor, can use 'tensor.device'

In [92]:
# Create a tensor
some_tensor = torch.rand(size=(3, 4))
some_tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.4761, 0.8378, 0.0918, 0.3864],
        [0.0362, 0.0993, 0.8118, 0.0745],
        [0.9137, 0.3528, 0.4521, 0.0237]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensor (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [94]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])

tensor + 100

tensor([101, 102, 103])

In [95]:
tensor * 10

tensor([10, 20, 30])

In [97]:
tensor - 10

tensor([-9, -8, -7])

In [98]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix multiplcation

Two main ways of performing multiplication in neural networks and deep learning:

* Element-wise multiplcation
* Matrix multiplication

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions must match: 
* (3, 2) @ (3, 2) won't work
* (2, 3) @ (3, 2) will work
* (3, 2) @ (2, 3) will work
2. The resulting matrix has the shape of the **outer dimensions**:
* (2, 3) @ (3, 2) -> (2, 2)
* (3, 2) @ (2, 3) -> (3, 3)

In [99]:
# Element-wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [102]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [103]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]

print(value)

tensor(14)
CPU times: user 2.03 ms, sys: 3.05 ms, total: 5.09 ms
Wall time: 8.53 ms


In [104]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 253 µs, sys: 141 µs, total: 394 µs
Wall time: 433 µs


tensor(14)

In [109]:
tensor_A = torch.tensor([
                            [1, 2],
                            [3, 4],
                            [5, 6]
                        ])

tensor_B = torch.tensor([
                            [7, 8],
                            [9, 10],
                            [5, 6]
                        ])

torch.matmul(tensor_A, tensor_B.T)

tensor([[ 23,  29,  17],
        [ 53,  67,  39],
        [ 83, 105,  61]])

In [110]:
tensor = torch.arange(0, 100, 5)
tensor

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
        90, 95])

In [111]:
tensor.argmin()

tensor(0)

In [112]:
tensor.argmax()

tensor(19)

In [113]:
tensor_A.shape

torch.Size([3, 2])

In [114]:
torch.reshape(tensor_A, shape=(2,3)).shape

torch.Size([2, 3])

In [115]:
x = torch.arange(0, 9)
x.shape

torch.Size([9])

In [117]:
x.reshape(9, 1)

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8]])

In [118]:
z = x.view(1, 9)

In [120]:
x_stacked = torch.stack([x, x, x, x, x], dim=1)
x_stacked

tensor([[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4],
        [5, 5, 5, 5, 5],
        [6, 6, 6, 6, 6],
        [7, 7, 7, 7, 7],
        [8, 8, 8, 8, 8]])

In [121]:
y = torch.zeros(2, 1, 2, 1, 2)
y

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

In [122]:
z = torch.squeeze(y)
z

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [126]:
sample_tensor = torch.rand(size=(3, 1, 1, 4, 1))

squeezed_tensor = sample_tensor.squeeze()


print(f'Sample tensor shape: {sample_tensor.shape}')
print(f'Squeezed tensor shape: {squeezed_tensor.shape}')

Sample tensor shape: torch.Size([3, 1, 1, 4, 1])
Squeezed tensor shape: torch.Size([3, 4])


In [139]:
print(f'Previous shape: {sample_tensor.shape}')

unsqueezed_tensor = sample_tensor.unsqueeze(dim=0)
print(f'\nNew tensor shape: {unsqueezed_tensor.shape}')

Previous shape: torch.Size([3, 1, 1, 4, 1])

New tensor shape: torch.Size([1, 3, 1, 1, 4, 1])
