In [2]:
import torch
print(torch.__version__)

2.3.1


## Introduction to Tensors

### Creating tensors

Scalar - single number - 0D- lower(a)

Vector - a number with direction and magnitude - 1D - lower(b)

Matrix - a two-dimensional array of numbers - 2D - Upper(A)

Tensor - a n-dimensional array of numbers - nD - Upper(B)

In [12]:
# Scalar
scalar = torch.tensor(21)
scalar

tensor(21)

In [14]:
scalar.ndim

0

In [15]:
# Get tensor back as Python int
scalar.item()

21

In [16]:
# Vector
vector = torch.tensor([21, 34])
vector

tensor([21, 34])

In [17]:
vector.ndim

1

In [18]:
vector.shape

torch.Size([2])

In [19]:
# MATRIX
MATRIX = torch.tensor([[21, 34], 
                       [53, 43]])

MATRIX

tensor([[21, 34],
        [53, 43]])

In [20]:
MATRIX.ndim

2

In [21]:
MATRIX.shape

torch.Size([2, 2])

In [59]:
# TENSOR
TENSOR = torch.tensor([
                        [
                            [1, 2, 3],
                            [4, 5, 6],
                            [7, 8, 9],
                            [10, 11, 12]
                        ], [
                            [1, 2, 3],
                            [4, 5, 6],
                            [7, 8, 9],
                            [10, 11, 12]
                        ],
                        [
                            [1, 2, 3],
                            [4, 5, 6],
                            [7, 8, 9],
                            [10, 11, 12]
                        ],
                        [
                            [1, 2, 3],
                            [4, 5, 6],
                            [7, 8, 9],
                            [10, 11, 12]
                        ]
                    ])

TENSOR2 = torch.tensor([
                        [
                            [1, 2, 3, 2, 4],
                            [4, 5, 6, 2, 4],
                            [7, 8, 9, 2, 4],
                            [10, 11, 12, 2, 4],
                            [10, 11, 12, 2, 4]
                        ],
                        [
                            [1, 2, 3, 2, 4],
                            [4, 5, 6, 2, 4],
                            [7, 8, 9, 2, 4],
                            [10, 11, 12, 2, 4],
                            [10, 11, 12, 2, 4]
                        ],
                        [
                            [1, 2, 3, 2, 4],
                            [4, 5, 6, 2, 4],
                            [7, 8, 9, 2, 4],
                            [10, 11, 12, 2, 4],
                            [10, 11, 12, 2, 4]
                        ],
                        [
                            [1, 2, 3, 2, 4],
                            [4, 5, 6, 2, 4],
                            [7, 8, 9, 2, 4],
                            [10, 11, 12, 2, 4],
                            [10, 11, 12, 2, 4]
                        ]
                    ])

#([4, 5, 5])
TENSOR2.shape

torch.Size([4, 5, 5])

In [46]:
TENSOR.ndim

3

In [47]:
TENSOR.shape

torch.Size([2, 4, 3])

In [48]:
TENSOR[0]

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])